### ISSUE TITLE
Does this work for files that have already been deleted?

### ISSUE THREAD

**Issue by NgJason** [WoLpH/dropbox-time-machine#2]
I deleted my files 6 months ago. I don't have time machine installed yet. Would this work to recover the files that I removed 6 months ago?

**Comment by wolph** [comment]
Hi, the script just uses the normal Dropbox system in the background so if they still have it available it will be there. 

The script is available at http://dropbox.wol.ph/ if you want to give it a try. No need to install it yourself.

**Comment by jilt** [comment]
Your demo isn't working anymore, would you help me running another demo instance using api 2 on my servers?

**Comment by wolph** [comment]
@jilt Unfortunately the dropbox API has changed in the mean time so this application won't work unless someone puts in significant time to get it to work again
